### ISSUE TITLE
Issue with husqvarna-automower package

### ISSUE THREAD

**Issue by Thomas55555** [home-assistant/wheels-custom-integrations#146]
My pypi package was added to the wheel with the pull request #126. In 308409df759f67ccdd783d99d07a56f9007ba3e2 it was deleted because of an issue with the package. How can I find out what issue it is, to fix it? Sorry, that I don't have an idea. It's the first package I created.

**Comment by MartinHjelmare** [comment]
I don't know the background to why the manifest was deleted. Looking at the library on PyPI, it's missing an `install_requires` parameter in the setup.py file. The library depends on `requests` and `requests-oauthlib`, so it needs to specify this dependency via `install_requires`.

https://packaging.python.org/discussions/install-requires-vs-requirements/
