### ISSUE TITLE
Bosch package is not built by wheels anymore

### ISSUE THREAD

**Issue by pszafer** [home-assistant/wheels-custom-integrations#540]
Hi,
I'm not sure if it is proper repo to ask. If not please help me to reach to proper repo.
I run github action `hacs/action@main`.

As far as I see logs it fetches 
- Alpine 3.14 image,
- building docker image
- running docker image
```
  Successfully tagged validate:latest
  [
    "bosch-thermostat-client==0.16.5"
  ]
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp47a8txqd
         cwd: /tmp/pip-install-tlo20hfh/cryptography
    Complete output (158 lines):
    running bdist_wheel
    running build
    running build_py

```

It ends with:
```
    error: [Errno 2] No such file or directory: 'cargo'
    ----------------------------------------
    ERROR: Failed building wheel for cryptography
  ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
  Validating requirements
```

I'm looking into: https://wheels.home-assistant.io/alpine-3.14/amd64/ and I see that last build of bosch_thermostat_client is from September.
Link to logs: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component/runs/4165110755?check_suite_focus=true

File attached as well
[5_Run hacsaction@main.txt](https://github.com/home-assistant/wheels-custom-integrations/files/7512788/5_Run.hacsaction%40main.txt)
.
Thanks for your help!

**Comment by pvizeli** [comment]
https://github.com/home-assistant/wheels-custom-integrations/issues/640
